### PR TITLE
Configurable asset glob

### PR DESCRIPTION
**Pull request by willcosgrove**
Per your recommendation on #3.  Hopefully this resembles what you had in mind!  If not, let me know, and I'll get it fixed.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Woaaahh I did *not* know that `cattr_accessor` _actually_ used a class attribute. I thought its whole point was to _avoid_ the dangers of class attributes. I wonder if I've ever actually used it anywhere! 


Ok, sorry I said `AssetPath` but I realize now that `AssetPath` is used for the path to the bundled JS, _not_ the path to the files to reload :S Kind of dumb of me to get those mixed up. Do you mind moving that config back to `AssetChangeSet`? Sorry I got confused :weary:

**Comment by willcosgrove** [comment]
No worries, yeah I thought it looked like a funny place for it.  I'll move that over to `AssetChangeSet`.

Do you want to stick with `cattr_accessor`, or move to some other solution?

**Comment by rmosolgo** [comment]
I think `cattr_accessor` is fine since nobody's extending that class, but I think the safest is: 

```ruby
  class << self 
    attr_accessor :asset_glob 
   end 
   self.asset_glob = "#{your-glob}"
```

**Comment by rmosolgo** [comment]
Ohhh, maybe this is what i was thinking of: http://apidock.com/rails/Class/class_attribute ¯\_(ツ)_/¯

**Comment by willcosgrove** [comment]
Ok, how does that look?  I switched to `class_attribute` which basically is doing what you mentioned above.  It's dependent on ActiveSupport, but since this whole gem is for Rails, I figure that's not a horrible thing.

**Comment by rmosolgo** [comment]
:money_with_wings:  :confetti_ball:

**Comment by rmosolgo** [comment]
Shipped as 0.4.0

**Comment by willcosgrove** [comment]
Sweet, thanks!

**Pull request merged**
